//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkTestJournals.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsPath : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsPath defaultInstance = ((SettingsPath)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsPath())));
        
        public static SettingsPath Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\Responsive-Batch-3.x" +
            "lsx")]
        public string Path_Batch3 {
            get {
                return ((string)(this["Path_Batch3"]));
            }
            set {
                this["Path_Batch3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\NegativeLogInInfo.xl" +
            "sx")]
        public string UsersNegative {
            get {
                return ((string)(this["UsersNegative"]));
            }
            set {
                this["UsersNegative"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\PositiveSearch.xlsx")]
        public string SearchPositive {
            get {
                return ((string)(this["SearchPositive"]));
            }
            set {
                this["SearchPositive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\NegativeSearch.xlsx")]
        public string SearchNegative {
            get {
                return ((string)(this["SearchNegative"]));
            }
            set {
                this["SearchNegative"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\FrameworkTestJournal" +
            "s\\\\FrameworkTestJournals\\\\TestData\\\\DataAdvansedSearch.xml")]
        public string DataAdvansedSearch {
            get {
                return ((string)(this["DataAdvansedSearch"]));
            }
            set {
                this["DataAdvansedSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\FrameworkTestJournal" +
            "s\\\\FrameworkTestJournals\\\\TestData\\\\PositiveDataForLogIn.xml")]
        public string PositiveDataLogIn {
            get {
                return ((string)(this["PositiveDataLogIn"]));
            }
            set {
                this["PositiveDataLogIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\FrameworkTestJournal" +
            "s\\\\FrameworkTestJournals\\\\TestData\\\\NegativeDataForLogIn.xml")]
        public string NegativeDataLogIn {
            get {
                return ((string)(this["NegativeDataLogIn"]));
            }
            set {
                this["NegativeDataLogIn"] = value;
            }
        }
    }
}
