//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkTestJournals {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsPath : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsPath defaultInstance = ((SettingsPath)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsPath())));
        
        public static SettingsPath Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\\\Framework\\\\Styling\\\\Responsive-Batch-3.xlsx")]
        public string Path_Batch3 {
            get {
                return ((string)(this["Path_Batch3"]));
            }
            set {
                this["Path_Batch3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\\\Framework\\\\PositiveLogInInfo.xlsx")]
        public string UsersPositive {
            get {
                return ((string)(this["UsersPositive"]));
            }
            set {
                this["UsersPositive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\\\Framework\\\\NegativeLogInInfo.xlsx")]
        public string UsersNegative {
            get {
                return ((string)(this["UsersNegative"]));
            }
            set {
                this["UsersNegative"] = value;
            }
        }
    }
}
