//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_3_LinqToXml.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class PathForFiles : global::System.Configuration.ApplicationSettingsBase {
        
        private static PathForFiles defaultInstance = ((PathForFiles)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PathForFiles())));
        
        public static PathForFiles Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\Task_3_LinqToXml\\\\Task_3_LinqToX" +
            "ml\\\\RD. HW - AT Lab#. 05 - Customers.xml")]
        public string Path {
            get {
                return ((string)(this["Path"]));
            }
            set {
                this["Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\Task_3_LinqToXml\\\\results\\\\SortB" +
            "yCountries.txt")]
        public string SortByCountries {
            get {
                return ((string)(this["SortByCountries"]));
            }
            set {
                this["SortByCountries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\Task_3_LinqToXml\\\\results\\\\Total" +
            "TurnoverMoreThanX.txt")]
        public string TotalTurnoverMoreThanX {
            get {
                return ((string)(this["TotalTurnoverMoreThanX"]));
            }
            set {
                this["TotalTurnoverMoreThanX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\Task_3_LinqToXml\\\\results\\\\Order" +
            "MoreThanX.txt")]
        public string OrderMoreThanX {
            get {
                return ((string)(this["OrderMoreThanX"]));
            }
            set {
                this["OrderMoreThanX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\Task_3_LinqToXml\\\\results\\\\Month" +
            "AndYearFirstOrder.txt")]
        public string MonthAndYearFirstOrder {
            get {
                return ((string)(this["MonthAndYearFirstOrder"]));
            }
            set {
                this["MonthAndYearFirstOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\Task_3_LinqToXml\\\\results\\\\Sorte" +
            "dMonthAndYearFirstOrder.txt")]
        public string SortedMonthAndYearFirstOrder {
            get {
                return ((string)(this["SortedMonthAndYearFirstOrder"]));
            }
            set {
                this["SortedMonthAndYearFirstOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\Task_3_LinqToXml\\\\results\\\\Custo" +
            "mersWithInvalidData.txt")]
        public string CustomersWithInvalidData {
            get {
                return ((string)(this["CustomersWithInvalidData"]));
            }
            set {
                this["CustomersWithInvalidData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Iryna_Bahatka1\\\\Documents\\\\Tasks.Net\\\\Task_3_LinqToXml\\\\results\\\\Avera" +
            "geCity.txt")]
        public string AverageCity {
            get {
                return ((string)(this["AverageCity"]));
            }
            set {
                this["AverageCity"] = value;
            }
        }
    }
}
