//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkTestJournals {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsPath : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsPath defaultInstance = ((SettingsPath)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsPath())));
        
        public static SettingsPath Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\irina\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\Responsive-Batch-3.xlsx")]
        public string Path_Batch3 {
            get {
                return ((string)(this["Path_Batch3"]));
            }
            set {
                this["Path_Batch3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\irina\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\PositiveLogInInfo.xlsx")]
        public string UsersPositive {
            get {
                return ((string)(this["UsersPositive"]));
            }
            set {
                this["UsersPositive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\irina\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\NegativeLogInInfo.xlsx")]
        public string UsersNegative {
            get {
                return ((string)(this["UsersNegative"]));
            }
            set {
                this["UsersNegative"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\irina\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\PositiveSearch.xlsx")]
        public string SearchPositive {
            get {
                return ((string)(this["SearchPositive"]));
            }
            set {
                this["SearchPositive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\irina\\\\Documents\\\\Tasks.Net\\\\JFramework\\\\NegativeSearch.xlsx")]
        public string SearchNegative {
            get {
                return ((string)(this["SearchNegative"]));
            }
            set {
                this["SearchNegative"] = value;
            }
        }
    }
}
